stages:
  - version
  - development
  - production


variables:
  AUTHOR: 'Ali Zahedigol'

.node: &node
  image: node:13
#  before_script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  tags:
    - node

.python: &python
  image: python:3.7
  before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get update -y && apt-get -y install openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  tags:
    - python


version:
  # Requires Node >= 10.13 version
  <<: *node
  stage: version
  only:
    refs:
    - master
    - develop
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
    - VERSION.txt


production:
  <<: *python
  stage: production
  environment:
    name: production
  script:
    - echo "Version is $(cat VERSION.txt)"
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --run='python manage.py migrate && python manage.py collectstatic --noinput '
  only:
    - master
  dependencies:
    - version
