# Generated by Django 3.2 on 2021-05-12 18:35

import appicons.utils
from django.db import migrations, models
import utilities.db.fields.filefields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file', utilities.db.fields.filefields.RestrictedFileField(upload_to=appicons.utils.get_file_path, verbose_name='File')),
                ('archive', utilities.db.fields.filefields.RestrictedFileField(blank=True, null=True, upload_to=appicons.utils.get_archive_path, verbose_name='Archive')),
            ],
            options={
                'verbose_name': 'App icon',
                'verbose_name_plural': 'App icons',
            },
        ),
    ]
